message:
  - ''
  - ' &6<< &fДобро пожаловать в семью &#00fbfb&lɴ&#00f9fb&lɪ&#00f8fc&lɢ&#00f6fc&lʜ&#00f5fc&lᴛ&#00f3fc&lʟ&#00f1fd&lᴏ&#00f0fd&lᴏ&#00eefd&lɴ! &6>>'
  - ''
  - '  &6{player}&f, мы искренне рады, что твой выбор'
  - '  &fпал именно на этот замечательный, как'
  - '  &fговорят в народе, Святой мир. Уверены, что'
  - '  &fс нашем количеством ивентов, ветвей развития'
  - '  & Ты точно не успеешь заскучать.'
  - '  &#00fbfb&lУ&#00fafb&lд&#00f9fb&lа&#00f7fc&lч&#00f6fc&lн&#00f5fc&lо&#00f4fc&lй &#00f3fc&lи&#00f2fc&lг&#00f0fd&lр&#00effd&lы &#00eefd&l!'
  - ''